#!/bin/bash

OPTIONS=""

if [ ${REDIS_MAX_MEMORY} ]; then
    OPTIONS=" --maxmemory $REDIS_MAX_MEMORY"
fi

if [ ${REDIS_MAX_MEMORY_POLICY} ]; then
    OPTIONS=" --maxmemory-policy $REDIS_MAX_MEMORY_POLICY"
fi

set -eu
cmd="$1"; shift

exec $cmd "$@" $OPTIONS
