#!/bin/bash

OPTIONS="$REDIS_EXTRA_PARAMETERS"

if [ -n "${REDIS_MAX_MEMORY}" ]; then
    OPTIONS+=" --maxmemory $REDIS_MAX_MEMORY"
fi

if [ -n "${REDIS_MAX_MEMORY_POLICY}" ]; then
    OPTIONS+=" --maxmemory-policy $REDIS_MAX_MEMORY_POLICY"
fi

if [ -n "${REDIS_DIR}" ]; then
    mkdir -p "$REDIS_DIR"
    chmod -R g+w "$REDIS_DIR"
    OPTIONS+=" --dir $REDIS_DIR"
fi

if [ -n "${REDIS_DBFILENAME}" ]; then
    OPTIONS+=" --dbfilename $REDIS_DBFILENAME"
fi

set -eu
cmd="$1"; shift

exec $cmd "$@" $OPTIONS
